/*
 * seniales.h
 *
 *  Created on: 15/06/2012
 *      Author: alejandro
 */

#ifndef SENIALES_H_
#define SENIALES_H_

typedef enum {
	SIG_NUEVA_VELOCIDAD			=0,
	SIG_NUEVA_INCLINACION		,
	SIG_NUEVA_PULSACIONES		,
	SIG_ROPTURA_CADENA			,
	SIG_SHOCK_DETECTADO			,
	SIG_CONFIG_VELOCIDAD_MAXIMA		,
	SIG_CONFIG_INCLINACION_MAXIMA		,
	SIG_CONFIG_PULSACIONES_MAXIMA		,
	SIG_CONFIG_RODADO					,
	SIG_CONFIG_COMENZAR_CONFIG	,
	SIG_CONFIG_FINALIZAR_CONFIG	,
	SIG_ACTIVAR_ALARMA			,
	SIG_DESACTIVAR_ALARMA		,
	SIG_MODULO_INICIAR			,
	SIG_COMIENZO_MOVIMIENTO		,
	SIG_FIN_MOVIMIENTO		,
	SIG_TIMEOUT					,
	SIG_ULTIMO_VALOR = SIG_TIMEOUT
} Signal_t;


#endif /* SENIALES_H_ */
